#!/usr/bin/env bash
# A Bash script that stops the 7-highlander process

# Find the PID(s) of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Stop the process using SIGTERM
if [ -n "$pid" ]; then
    # Sending SIGTERM using /proc interface
    echo "$pid" | xargs -n 1 kill -15
fi
