#!/usr/bin/env bash
# A Bash script that attempts to stop the 7-highlander process without using kill or killall

# Find the PID(s) of the 7-highlander process
for pid in $(pgrep -f 7-highlander); do
    # Send SIGTERM using pkill (alternative to kill/killall)
    pkill -TERM -P "$pid" 2>/dev/null
done
